version: '3.7'

services:
  web:
    build: .
    command: python wsgi.py
    ports:
      - 8000:5000
    links:
      - db
    depends_on:
      - db

  db:
    image: library/postgres:latest
    environment:
      - POSTGRES_USER=cursor
      - POSTGRES_PASSWORD=very_secret_password
      - POSTGRES_DB=cursor_sqlalchemy_db
    ports:
    - 5432:5432
