version: '3.7'

services:
  web:
    build: .
    command: python app.py
    ports:
      - 8000:5000

  db:
    image: library/postgres:latest
    environment:
      - POSTGRES_USER=cursor
      - POSTGRES_PASSWORD=very_secret_password
      - POSTGRES_DB=cursor_sqlalchemy_db